### PR TITLE
Updated the available icons for additional color states

### PR DESCRIPTION
**Pull request by scottmerker**
Added 5 new color states for icons via SVG, and one placeholder for a SVG future state icon.  Updated the icons.less file and the foundation > icons page to reflect this addition.

**New icon colors:**
* Primary
* Info
* Success
* Warning
* Danger
* Mask (for future use)

### CODE REVIEW

**Comment by bmathews** [comment]
:+1:

**Comment by arvalarva** [comment]
Hi, Scott,


Have we done a 508 test on the yellow icon state?


Thanks,

Arva


________________________________

**Comment by scottmerker** [comment]
My assumption is the primary palette has passed 508 right?  We aren't
moving beyond those primary brand colors here:

/docs/foundation/colors.html

What are your thoughts?

Scott

**Comment by scottmerker** [comment]
Comparing other applications, I'm suggesting we set the warning color to #e8ae37, which is a darker, richer color and provides more contrast.

**Comment by AaronUXD** [comment]
I believe the color change would have to be made to the @brand-warning color which should update the color on all warnings. I think the current one was just changed to the light one though. As all the projects need to update it, we should be sure of the new color before having all the projects change it again.

------------------------------------
aaron.pepe@uspto.gov
(571) 272-7185 | MDW 4D30

**Pull request merged**
