### PR TITLE
add new Guides section

### LINKED ISSUE #97: Create new Guides section
__Guides template__
- [ ] Add a new top level section to the site named “Guides” (after resources, before changelog). Each page should include:

- Text content describing template 
- Picture of template
- Ability to download template
- Downloadable ZIP file containing all the template files

__Left navigation__
- [ ] Create a new left side navigation that lists all of the available guides.

### PR DESCRIPTION
**Pull request by vizui**
closes #97

### CODE REVIEW

**Comment by scottmerker** [comment]
We'll also want to update the _config_release.yml file before the next release.

**Comment by scottmerker** [comment]
@AaronUXD Merged, and available in the future guide - http://uspto.github.io/designpatterns/docs/resources.html

**Comment by arvalarva** [comment]
I don't see "Guides" section. What am I looking for?

**Comment by vizui** [comment]
@arvalarva In the top navigation there's a new link to "Guides":
http://uspto.github.io/designpatterns/docs/guides/project/project-close.html

**Comment by scottmerker** [comment]
You might need to do a ctrl-f5 / clear cache refresh.

**Pull request merged**
